### ISSUE TITLE
Lakers versus Celtics and the NBA Playoffs [Sep, 1989]

### ISSUE THREAD

**Issue by kandahar-dev** [caiiiycuk/dos.zone#2]
Lakers vs Celtics es un juego de baloncesto de los equipos de la NBA. La jugabilidad está orientado a la acción, con énfasis en la ofensiva. Jugar un juego de exhibición o tratar de ganar el título de la NBA en el playoff en el modo torneo. Un modo de temporada no está disponible. Se puede hacer sustituciones por el cansancio de los jugadores, pero no hay otras opciones de gestión. El juego cuenta con diez equipos de la temporada '88-'89 de la NBA, incluyendo el Este y el Oeste All-Stars. Usted puede jugar con algunos de los nombres más grandes en la historia de la NBA, incluyendo Kareem, Bird, Jordan y Ewing. Varios jugadores estrella tiene su propia firma de mover.
--
** DO NOT REMOVE **
`./build/dz.js dc update --key dos/lakers-versus-celtics-and-the-nba-playoffs --locale es`

**Comment by caiiiycuk** [comment]
Done! Thank you!
